In [22]:
import numpy as np

In [27]:
from numpy import *
matriks = np.random.randint(1,5,(3,30))
print(matriks)

[[3 2 1 2 1 4 3 2 4 2 3 1 4 2 2 1 4 3 1 4 3 3 2 4 1 2 2 3 3 4]
 [2 2 3 2 4 3 2 1 2 3 3 4 2 2 2 2 2 2 2 1 3 1 2 4 4 2 4 2 3 1]
 [2 2 2 2 3 4 4 1 2 4 2 3 3 1 2 4 1 2 1 1 2 2 1 4 4 2 4 1 1 1]]
